// Placeholder for database types generated by Supabase CLI
// Run: npx supabase gen types typescript --local > src/types/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      workspaces: {
        Row: {
          id: string
          name: string
          slug: string
          owner_user_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          owner_user_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          owner_user_id?: string
          created_at?: string
          updated_at?: string
        }
      }
      workspace_members: {
        Row: {
          id: string
          workspace_id: string
          user_id: string
          role: string
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          user_id: string
          role: string
          created_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          user_id?: string
          role?: string
          created_at?: string
        }
      }
      templates: {
        Row: {
          id: string
          workspace_id: string | null
          key: string
          name: string
          description: string | null
          category: string | null
          version: string
          cover_url: string | null
          schema_json: Json
          default_config: Json
          is_system: boolean
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id?: string | null
          key: string
          name: string
          description?: string | null
          category?: string | null
          version?: string
          cover_url?: string | null
          schema_json: Json
          default_config: Json
          is_system?: boolean
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string | null
          key?: string
          name?: string
          description?: string | null
          category?: string | null
          version?: string
          cover_url?: string | null
          schema_json?: Json
          default_config?: Json
          is_system?: boolean
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      projects: {
        Row: {
          id: string
          workspace_id: string
          template_id: string | null
          name: string
          slug: string
          description: string | null
          status: string
          draft_config: Json
          cover_asset_id: string | null
          created_by: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          template_id?: string | null
          name: string
          slug: string
          description?: string | null
          status?: string
          draft_config: Json
          cover_asset_id?: string | null
          created_by: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          template_id?: string | null
          name?: string
          slug?: string
          description?: string | null
          status?: string
          draft_config?: Json
          cover_asset_id?: string | null
          created_by?: string
          created_at?: string
          updated_at?: string
        }
      }
      scenes: {
        Row: {
          id: string
          project_id: string
          scene_key: string
          scene_type: string
          name: string
          position: number
          duration_ms: number
          trigger_mode: string
          enabled: boolean
          config: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          project_id: string
          scene_key: string
          scene_type: string
          name: string
          position: number
          duration_ms: number
          trigger_mode?: string
          enabled?: boolean
          config: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          scene_key?: string
          scene_type?: string
          name?: string
          position?: number
          duration_ms?: number
          trigger_mode?: string
          enabled?: boolean
          config?: Json
          created_at?: string
          updated_at?: string
        }
      }
      assets: {
        Row: {
          id: string
          workspace_id: string
          project_id: string | null
          type: string
          bucket: string
          storage_path: string
          original_name: string
          mime_type: string
          size_bytes: number
          width: number | null
          height: number | null
          duration_ms: number | null
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          project_id?: string | null
          type: string
          bucket: string
          storage_path: string
          original_name: string
          mime_type: string
          size_bytes: number
          width?: number | null
          height?: number | null
          duration_ms?: number | null
          metadata?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          project_id?: string | null
          type?: string
          bucket?: string
          storage_path?: string
          original_name?: string
          mime_type?: string
          size_bytes?: number
          width?: number | null
          height?: number | null
          duration_ms?: number | null
          metadata?: Json | null
          created_at?: string
        }
      }
      publications: {
        Row: {
          id: string
          project_id: string
          version: number
          slug: string
          snapshot: Json
          status: string
          published_by: string
          published_at: string
          unpublished_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          project_id: string
          version: number
          slug: string
          snapshot: Json
          status?: string
          published_by: string
          published_at?: string
          unpublished_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          project_id?: string
          version?: number
          slug?: string
          snapshot?: Json
          status?: string
          published_by?: string
          published_at?: string
          unpublished_at?: string | null
          created_at?: string
        }
      }
      audit_logs: {
        Row: {
          id: string
          workspace_id: string
          user_id: string | null
          action: string
          entity_type: string
          entity_id: string | null
          metadata: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          workspace_id: string
          user_id?: string | null
          action: string
          entity_type: string
          entity_id?: string | null
          metadata?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          workspace_id?: string
          user_id?: string | null
          action?: string
          entity_type?: string
          entity_id?: string | null
          metadata?: Json | null
          created_at?: string
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
